# Autogenerated by maintainers/scripts/bootstrap-files/refresh-tarballs.bash as:
# $ ./refresh-tarballs.bash --targets=x86_64-unknown-linux-musl
#
# Metadata:
# - nixpkgs revision: a871af02f1b36d22fadbc8ea5ad5f7fb22cc68e7
# - hydra build: https://hydra.nixos.org/job/nixpkgs/trunk/stdenvBootstrapTools.x86_64-unknown-linux-musl.build/latest
# - resolved hydra build: https://hydra.nixos.org/build/309181177
# - instantiated derivation: /nix/store/yai9a5815wshgm8pdqwz5bc4q960m5s0-stdenv-bootstrap-tools.drv
# - output directory: /nix/store/9w501b5zzkrh2x6azc03gm8d9w1d28zr-stdenv-bootstrap-tools
# - build time: Sun, 05 Oct 2025 20:28:48 +0000
{
  bootstrapTools = import <nix/fetchurl.nix> {
    url = "http://tarballs.nixos.org/stdenv/x86_64-unknown-linux-musl/a871af02f1b36d22fadbc8ea5ad5f7fb22cc68e7/bootstrap-tools.tar.xz";
    hash = "sha256-kAiD/YFoOg/IuAk32Xq0XUYhUGRe4MO5abqUiYv9j2c=";
  };
  busybox = import <nix/fetchurl.nix> {
    url = "http://tarballs.nixos.org/stdenv/x86_64-unknown-linux-musl/a871af02f1b36d22fadbc8ea5ad5f7fb22cc68e7/busybox";
    hash = "sha256-dx+s6vQKo9v+k3+Th1fOeBHvcPCYoGzFL6h9nQPKcZc=";
    executable = true;
  };
}
