# Autogenerated by maintainers/scripts/bootstrap-files/refresh-tarballs.bash as:
# $ ./refresh-tarballs.bash --targets=x86_64-unknown-linux-musl
#
# Metadata:
# - nixpkgs revision: 01b6809f7f9d1183a2b3e081f0a1e6f8f415cb09
# - hydra build: https://hydra.nixos.org/job/nixpkgs/trunk/stdenvBootstrapTools.x86_64-unknown-linux-musl.build/latest
# - resolved hydra build: https://hydra.nixos.org/build/310745962
# - instantiated derivation: /nix/store/v2j8fy2az0k2q7w7jjy1jcm3fn1p704x-stdenv-bootstrap-tools.drv
# - output directory: /nix/store/l916l2hh3xn65x07j3h0p6qkxc9r3y9n-stdenv-bootstrap-tools
# - build time: Wed, 22 Oct 2025 21:42:38 +0000
{
  bootstrapTools = import <nix/fetchurl.nix> {
    url = "http://tarballs.nixos.org/stdenv/x86_64-unknown-linux-musl/01b6809f7f9d1183a2b3e081f0a1e6f8f415cb09/bootstrap-tools.tar.xz";
    hash = "sha256-RrQrgMJiN77YbwCkpeNivtmJzryt0kJo/xR+UduLedI=";
  };
  busybox = import <nix/fetchurl.nix> {
    url = "http://tarballs.nixos.org/stdenv/x86_64-unknown-linux-musl/01b6809f7f9d1183a2b3e081f0a1e6f8f415cb09/busybox";
    hash = "sha256-4DD7VQNeKFeRpKQVJZ/PBtTGZpAMR/+od9/di++6ApY=";
    executable = true;
  };
}
