# Autogenerated by maintainers/scripts/bootstrap-files/refresh-tarballs.bash as:
# $ ./refresh-tarballs.bash --targets=x86_64-unknown-linux-musl
#
# Metadata:
# - nixpkgs revision: d33e926c80e6521a55da380a4c4c44a7462af405
# - hydra build: https://hydra.nixos.org/job/nixpkgs/trunk/stdenvBootstrapTools.x86_64-unknown-linux-musl.build/latest
# - resolved hydra build: https://hydra.nixos.org/build/307295135
# - instantiated derivation: /nix/store/mjy44g5029hl0c680rhjc5csdsq6saay-stdenv-bootstrap-tools.drv
# - output directory: /nix/store/1hqjy0ppprcnn70a592svfzzcgg2s7cv-stdenv-bootstrap-tools
# - build time: Thu, 11 Sep 2025 10:42:25 +0000
{
  bootstrapTools = import <nix/fetchurl.nix> {
    url = "http://tarballs.nixos.org/stdenv/x86_64-unknown-linux-musl/d33e926c80e6521a55da380a4c4c44a7462af405/bootstrap-tools.tar.xz";
    hash = "sha256-fCjApDDtTcQ4DfEH0P34MwuNRTTj0BTpS1669n8q7nU=";
  };
  busybox = import <nix/fetchurl.nix> {
    url = "http://tarballs.nixos.org/stdenv/x86_64-unknown-linux-musl/d33e926c80e6521a55da380a4c4c44a7462af405/busybox";
    hash = "sha256-c6JDkuQLFVgbybMqFqzdQ6R6KX+Okk2V25ku2qnNVXI=";
    executable = true;
  };
}
